### PR TITLE
Replace tab with space characters to fix --> indentation for make setup

### PR DESCRIPTION
**Pull request by tjyang**
Thank you for your interest in contributing to Checkmk!
Consider looking into [Readme](https://github.com/Checkmk/checkmk#want-to-contribute) regarding process details.

## General information
Replace tab with space characters to fix --> indentation for make setup

## Proposed changes
original @echo setup line has tab key to messed up the indentation,  --> was shifted to left by once character.
```
[me@al9t01 checkmk]$ git diff Makefile
diff --git a/Makefile b/Makefile
index 4879e3d365..9119d90016 100644
--- a/Makefile
+++ b/Makefile
@@ -63,7 +63,7 @@ endif
         protobuf-files

 help:
-       @echo "setup                          --> Prepare system for development and building"
+       @echo "setup                          --> Prepare system for development and building"
        @echo "make dist                      --> Create source tgz for later building of rpm/deb and livestatus tgz"
        @echo "make rpm                       --> Create rpm package"
        @echo "make deb                       --> Create deb package"
[me@al9t01 checkmk]$ git log -1
commit 026cfccaf90836c9dd26524e166d67e050900780 (HEAD -> master, origin/master, origin/HEAD)
Author: Andreas Boesl <andreas.boesl@checkmk.com>
Date:   Mon Jul 17 11:39:52 2023 +0200

    14206 FIX Improved checker performance for hosts using HW/SW inventory checks

    Change-Id: If039149525ae30eee309c39f733fd363824ee7db
[me@al9t01 checkmk]$
```

### CODE REVIEW

**Comment by tjyang** [comment]
recheck

**Comment by tjyang** [comment]
I have read the CLA Document and I hereby sign the CLA or my organization already has a signed CLA.

**Comment by tjyang** [comment]
- Before 

image

- After

image

**Comment by si-23** [comment]
Hi,
Thank you for your contribution! This will be merged shortly.

**Pull request closed without merging**
