### PR TITLE
New default path for nvidia-smi.exe

### PR DESCRIPTION
**Pull request by bili123**
The path to nvidia-smi.exe seems to have changed to "C:\Windows\System32\nvidia-smi.exe".  I couldn't find official information by Nvidia, but that's the path on my local system and you can find this in several Stackoverflow discussions and also here on Microsoft:  https://learn.microsoft.com/de-de/azure/databox-online/azure-stack-edge-gpu-deploy-virtual-machine-install-gpu-extension?tabs=windows#verify-driver-installation

### CODE REVIEW

**Comment by bili123** [comment]
have read the CLA Document and I hereby sign the CLA or my organization already has a signed CLA.

**Comment by bili123** [comment]
recheck

**Comment by bili123** [comment]
I have read the CLA Document and I hereby sign the CLA or my organization already has a signed CLA.

**Comment by bili123** [comment]
recheck

**Comment by TimotheusBachinger** [comment]
Dear Checkmk Contributor! Unfortunately, we had to re-write our git-repo history, rendering your PR auto-closed. We will therefore rebase your PR onto the current master and reopen it again. Sorry for the inconvenience.

**Comment by TimotheusBachinger** [comment]
Dear Contributor. Unfortunately, we learned that re-opening a PR which was force-rebased, is not possible (see https://github.com/isaacs/github/issues/361). Therefore we kindly ask you to create a new PR for your change. We apologize for the circumstances and will implement technical measures to prevent such incidents in the future.

**Pull request closed without merging**
