### PR TITLE
Fix get_bloat for Windows and use PGPASSFILE

### PR DESCRIPTION
**Pull request by marcohald**
## Bug reports

Please include:

+ Your operating system name and version
Windows Server 2019
+ Detailed steps to reproduce the bug
1. use more than 3 Postgres DBs
Then the get_bloat crashes with "The command line is too long."

2. Set a System Environment Variable for the PGPASSFILE
It get's overwritten by an empty String
## Proposed changes

This commit fixes two issue.
1. The get_bloat executes psql for each database. This is necessary because otherwise it exceeds the maximum 8191 characters limit of windows https://learn.microsoft.com/en-us/troubleshoot/windows-client/shell-experience/command-line-string-limitation Which triggers the error "The command line is too long." I observed it with 3 databases

2. The PGPASSFILE Env varaible is only overwritten by the instance pg_passfile when it is not empty. In this way it is possible to use a system wide PGPASSFILE evnironment variable.

### CODE REVIEW

**Comment by si-23** [comment]
Hi,
thank you for uploading a PR.
Please resolve the merge conflicts.

**Comment by marcohald** [comment]
I have read the CLA Document and I hereby sign the CLA or my organization already has a signed CLA.

**Comment by si-23** [comment]
Hi,
I'm very sorry that I have to ask you again: Please can you rebase your PR?
We're are currently working on a similar topic: "Argument list too long" and we may include your PR in our changes.

I'm sorry for the inconvenience!
BG

**Comment by TimotheusBachinger** [comment]
Dear Checkmk Contributor! Unfortunately, we had to re-write our git-repo history, rendering your PR auto-closed. We will therefore rebase your PR onto the current master and reopen it again. Sorry for the inconvenience.

**Comment by TimotheusBachinger** [comment]
Dear Contributor. Unfortunately, we learned that re-opening a PR which was force-rebased, is not possible (see https://github.com/isaacs/github/issues/361). Therefore we kindly ask you to create a new PR for your change. We apologize for the circumstances and will implement technical measures to prevent such incidents in the future.

**Pull request closed without merging**
