### PR TITLE
Implement service state filter for quicksearch widget

### PR DESCRIPTION
**Pull request by moschlar**
## General information

I use the quicksearch sidebar widget a lot and I often find myself wanting to see all services matching a description that are not OK - so I thought it would be nice to have an additional filter so that I can query for e.g. `s:Certificate st:1 st:2`.

## Proposed changes

I implemented a `ServiceStateMatchPlugin` class to accomplish this - it works quite well now!

Open tasks/questions:
- What is the first element of the return value of `get_matches` supposed to be?
- How to correctly display the "preselected" quicksearch filters in the graphical filter selection dialog?

### CODE REVIEW

**Comment by moschlar** [comment]
I don't understand why the mypy tests fail - IMHO the actual return value types match the expected ones...

**Comment by moschlar** [comment]
I have read the CLA Document and I hereby sign the CLA or my organization already has a signed CLA.

**Comment by moschlar** [comment]
@Checkmk Ping?

**Comment by TimotheusBachinger** [comment]
Dear Checkmk Contributor! Unfortunately, we had to re-write our git-repo history, rendering your PR auto-closed. We will therefore rebase your PR onto the current master and reopen it again. Sorry for the inconvenience.

**Comment by moschlar** [comment]
I have just rebased it myself already!

**Comment by TimotheusBachinger** [comment]
Hi @moschlar thanks for rebasing. However it still seems that your PR has not an up-to-date state (we still see those 10k commits in the header). Maybe you need to update also your PR?

**Comment by moschlar** [comment]
I think I can't do that because it's closed...

But I could just start a new one?

**Comment by TimotheusBachinger** [comment]
Starting a new one would be an option but we're facing the issue with 52 PRs and all the comments etc would be lost...
I just found this hint, can you try that on your end?
https://gist.github.com/robertpainsi/2c42c15f1ce6dab03a0675348edd4e2c

**Comment by moschlar** [comment]
I tried, but I don't think I have the permission to re-open the PR!

**Comment by TimotheusBachinger** [comment]
Dear Contributor. Unfortunately, we learned that re-opening a PR which was force-rebased, is not possible (see https://github.com/isaacs/github/issues/361). Therefore we kindly ask you to create a new PR for your change. We apologize for the circumstances and will implement technical measures to prevent such incidents in the future.

**Pull request closed without merging**
