### PR TITLE
new txt mapping for PS redundancy lost

### PR DESCRIPTION
**Pull request by m3rlinux**
Some DELL HW doesn't show correct state for PSU(s), but PS Redundancy is always correctly recognized.

With this mapping at least the plugin raise an alert if "PS Redundancy" sensor shows "Redundancy Lost"

### CODE REVIEW

**Comment by m3rlinux** [comment]
I have read the CLA Document and I hereby sign the CLA or my organization already has a signed CLA.

**Comment by m3rlinux** [comment]
recheck

**Comment by englertor** [comment]
Hi m3rlinux, 

thank you for your contribution! 
Unfortunately, we've had some issues in the definition of our upstream pipeline regarding gcc-13. 
Please be so kind to rebase your PR on our latest master and the tests should pass fine afterwards. 

Best
Torsten

**Comment by englertor** [comment]
Hi m3rlinux,

I've added your PR to our internal tracking. 
There is nothing left to do from your side.

Best
Torsten

**Pull request closed without merging**
