### PR TITLE
Add SNMP OID to support IBM 4500 tape library

### PR DESCRIPTION
**Pull request by schorschii**
This change adds an additional OID to get more information from IBM 4500 tape libraries via SNMP.

Special thanks to @Yogibaer75 !

### CODE REVIEW

**Comment by schorschii** [comment]
I have read the CLA Document and I hereby sign the CLA or my organization already has a signed CLA.

**Comment by schorschii** [comment]
recheck

**Comment by Yogibaer75** [comment]
@englertor This problem with internal errors inside the workflows should not lead to stale/closed PRs

**Comment by englertor** [comment]
@Yogibaer75 
True. I'll forward it and track the PR manually to avoid it going stale.

**Comment by englertor** [comment]
Hi @schorschii @Yogibaer75 ,

We've had some issues in the definition of our upstream pipeline regarding gcc-13. Those are fixed now.
Please be so kind to rebase your PR on our latest master and the tests should pass fine afterwards.

Sorry about the inconvenience.

Best
Torsten

**Comment by englertor** [comment]
@schorschii thanks for the rebase. It seems there is another issue though :-/. Apologies. 

We are on it.

**Comment by englertor** [comment]
@schorschii @Yogibaer75 

Meanwhile, we have fixed the other failures well. 
I've added the PR to our internal tracking. 

There is nothing left to do from your side. 

Best
Torsten

**Comment by logan-connolly** [comment]
Hi @schorschii and @Yogibaer75 thank you for your contribution! :)

You can find the details of your change in the following [werk](https://checkmk.com/werk/17359).

**Pull request closed without merging**
