### PR TITLE
Update check_mk_agent.solaris

### PR DESCRIPTION
**Pull request by buzz-de**
Adding the option for using ipmitool

### CODE REVIEW

**Review by mo-ki — CHANGES_REQUESTED** [review]
Hi! It seems this copy&paste from the Linux agent (which is good).
I've been trying to gradually align the Linux, Solaris, AIX, OpenWRT and FreeBSD agents by using these funny "COMMON AGENT CODE" markers. They are meant to ensure that the affected code snippets do not diverge. Can you put the section into one of those blocks?

I suggest line 554, before `section_job`. You'd have to adjust all five agents such that `make -C tests test-unit-shell` test is happy again.

**Comment by buzz-de** [comment]
Hi mo-ki,

it's the first time I'm using Github, appologize for dumb questions. I changed the code but can't run the checks because system says "First-time contributors need a maintainer to approve running workflows". Is there a way to grant me rights to run a check?

**Comment by mo-ki** [comment]
I approved the checks; but you should be able to run the command mentioned above locally. It would faill for this change I believe: The lines between `# BEGIN COMMON AGENT CODE` and `# END COMMON AGENT CODE` have to be the same _verbatim_ in all five agents, so you'll have to adjust all of them.

**Comment by TimotheusBachinger** [comment]
Dear Checkmk Contributor! Unfortunately, we had to re-write our git-repo history, rendering your PR auto-closed. We will therefore rebase your PR onto the current master and reopen it again. Sorry for the inconvenience.

**Comment by TimotheusBachinger** [comment]
Dear Contributor. Unfortunately, we learned that re-opening a PR which was force-rebased, is not possible (see https://github.com/isaacs/github/issues/361). Therefore we kindly ask you to create a new PR for your change. We apologize for the circumstances and will implement technical measures to prevent such incidents in the future.

**Pull request closed without merging**
