### PR TITLE
FIX for Victoria Metrics

### PR DESCRIPTION
**Pull request by m3rlinux**
## General information

Using Special Agent "prometheus" with Prometheus embedded in Victoria Metrics.

### CODE REVIEW

**Comment by m3rlinux** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by m3rlinux** [comment]
receck

**Comment by m3rlinux** [comment]
recheck

**Comment by m3rlinux** [comment]
I have read the CLA Document and I hereby sign the CLA or my organization already has a signed CLA.

**Comment by m3rlinux** [comment]
recheck

**Comment by m3rlinux** [comment]
news?

**Comment by TimotheusBachinger** [comment]
Dear Checkmk Contributor! Unfortunately, we had to re-write our git-repo history, rendering your PR auto-closed. We will therefore rebase your PR onto the current master and reopen it again. Sorry for the inconvenience.

**Comment by TimotheusBachinger** [comment]
Dear Contributor. Unfortunately, we learned that re-opening a PR which was force-rebased, is not possible (see https://github.com/isaacs/github/issues/361). Therefore we kindly ask you to create a new PR for your change. We apologize for the circumstances and will implement technical measures to prevent such incidents in the future.

**Pull request closed without merging**
