### PR TITLE
Added OIDs for Enviromux 5D

### PR DESCRIPTION
**Pull request by Ma7h1**
Added Enviromux 5D OIDs for the Enviromux checks.

### CODE REVIEW

**Comment by Yogibaer75** [comment]
I think there is a little bit missing in the code. At the moment only the new sections are detected but there is no check working with the new section. It would be better if the new sections supersede the other section if found. But that is only my opinion.

**Comment by Ma7h1** [comment]
[dw.zip](https://github.com/tribe29/checkmk/files/10517780/dw.zip)

**Comment by Yogibaer75** [comment]
> Why there should be new sections?

Your change created five new sections with name  - "enviromux5", "enviromux_aux5" and so on.
But you have no service who consumes this sections. All the services have the old names inside.
Like this example here.
`
register.check_plugin(
    name="enviromux",
    service_name="Sensor %s",
    discovery_function=discover_enviromux_temperature,
    check_function=check_enviromux_temperature,
    check_default_parameters={},
    check_ruleset_name="temperature",
)
`
Your "enviromux5" cannot be used by this check.

**Comment by Ma7h1** [comment]
But there are all there! This section registration uses the informations of the oid tree and passes to the normal parse function after that the section is called "enviromux", "enviromux_..." etc.
Thats the reason with all Sections uses the "parsed_section_name", there is no need for a new check/discovery or even parsing.

**Comment by Yogibaer75** [comment]
Sorry i was not reading the parsed section name.

**Comment by Ma7h1** [comment]
You can see this in your documentation under 
https://<CMK-SERVER>/<CMK-SITE>/check_mk/plugin-api/apidoc/cmk/cmk.base.plugins.agent_based.agent_based_api.v1.register.html?highlight=parsed_section_name
or 
`parsed_section_name (Optional[str]) – The name under which the parsed section will be available to the plugins. Defaults to the original name.`

**Comment by TLI29** [comment]
FYI, we are extending the Enviromux Check already with other changes. We need to consolidate both changes, so we kindly ask for some patience.

**Pull request closed without merging**
