### PR TITLE
fix(cmctc): crash fix in which a unique_name is given but not the value_store

### PR DESCRIPTION
**Pull request by moelrobi**
## General information

While upgrading my CheckMK site from 2.2.0-p27 to 2.3.0-p6 my checks for or Rittal LCPs crashed.
This behavior is fixed with this pull request.

### Your operating system name and version

Debian 12 Bookworm

### Any details about your local setup that might be helpful in troubleshooting

Standard installation of CheckMK, no special configuration 

### Detailed steps to reproduce the bug

Run a temperature check on any rittal lcps

### An agent output or SNMP walk

Unfortunately, I can't provide you with an SNMP walk from our lcps

### The ID of a submitted crash report for reference (if applicable)

`c68eec18-27d3-11ef-b844-005056a3621d`

### What is the expected behavior?

A successful check with temperature data

### What is the observed behavior?

Crash - See crash report

### CODE REVIEW

**Comment by moelrobi** [comment]
I have read the CLA Document and I hereby sign the CLA or my organization already has a signed CLA.

**Comment by TimotheusBachinger** [comment]
Dear Checkmk Contributor! Unfortunately, we had to re-write our git-repo history, rendering your PR auto-closed. We will therefore rebase your PR onto the current master and reopen it again. Sorry for the inconvenience.

**Comment by TimotheusBachinger** [comment]
Dear Contributor. Unfortunately, we learned that re-opening a PR which was force-rebased, is not possible (see https://github.com/isaacs/github/issues/361). Therefore we kindly ask you to create a new PR for your change. We apologize for the circumstances and will implement technical measures to prevent such incidents in the future.

**Comment by TimotheusBachinger** [comment]
Hi @moelrobi thanks also for the PR - in the meantime we had it fixed with https://checkmk.com/werk/16246

**Pull request closed without merging**
