### PR TITLE
Make Hyper-V plugin more explicit

### PR DESCRIPTION
**Pull request by kleinski**
### Problem

The problem occurs when the VMWare PowerCLI module is also installed on a system. In this case, calling the Get-VM cmdlet leads to the following error:

_Get-VM You are not currently connected to any servers. Please connect first using a Connect cmdlet._

### Reason

The reason is that the Get-VM cmdlet of the PowerCLI module is incorrectly used because there is an overlap in the naming of the Hyper-V cmdlet and the PowerCLI cmdlet.

### Solution

The solution to this is to specify the name of the cmdlet absolutely: _Hyper-V\Get-VM_ instead of _Get-VM_

### CODE REVIEW

**Comment by kleinski** [comment]
I have read the CLA Document and I hereby sign the CLA or my organization already has a signed CLA.

**Comment by kleinski** [comment]
I have read the CLA Document and I hereby sign the CLA or my organization already has a signed CLA.

**Comment by englertor** [comment]
recheck

**Comment by englertor** [comment]
recheck

**Comment by kleinski** [comment]
recheck

**Comment by TimotheusBachinger** [comment]
Dear Checkmk Contributor! Unfortunately, we had to re-write our git-repo history, rendering your PR auto-closed. We will therefore rebase your PR onto the current master and reopen it again. Sorry for the inconvenience.

**Comment by TimotheusBachinger** [comment]
Dear Contributor. Unfortunately, we learned that re-opening a PR which was force-rebased, is not possible (see https://github.com/isaacs/github/issues/361). Therefore we kindly ask you to create a new PR for your change. We apologize for the circumstances and will implement technical measures to prevent such incidents in the future.

**Pull request closed without merging**
