### PR TITLE
Adding ss as alternative to netstat

### PR DESCRIPTION
**Pull request by vafgoettlich**
- netstat seams to be deprecated
- ss is installed as "the new default" i. E. on debian
- just using ss if it is installed instead of netstat

### CODE REVIEW

**Comment by vafgoettlich** [comment]
I have read the CLA Document and I hereby sign the CLA or my organization already has a signed CLA.

**Comment by vafgoettlich** [comment]
I have read the CLA Document and I hereby sign the CLA or my organization already has a signed CLA.

**Comment by vafgoettlich** [comment]
Is there still anything todo from my side?

**Comment by dnlldl** [comment]
This is a very welcomed change, thank you for this. Most systems ship with `ss` by default nowadays.

**Comment by TimotheusBachinger** [comment]
Dear Checkmk Contributor! Unfortunately, we had to re-write our git-repo history, rendering your PR auto-closed. We will therefore rebase your PR onto the current master and reopen it again. Sorry for the inconvenience.

**Comment by TimotheusBachinger** [comment]
Dear Contributor. Unfortunately, we learned that re-opening a PR which was force-rebased, is not possible (see https://github.com/isaacs/github/issues/361). Therefore we kindly ask you to create a new PR for your change. We apologize for the circumstances and will implement technical measures to prevent such incidents in the future.

**Pull request closed without merging**
