### PR TITLE
Added compability for python3 in mk_sap.py

### PR DESCRIPTION
**Pull request by stefan7018**
After Upgrade to 2.0.0p3 I've noticed the sap checks are only working with python2 because required python-sapnwrfc-0.19 isn't maintained anymore and not available for python3.

So I've rewritten the check to use maintained pyrfc.

Its a quick and dirty implementation I think some refactoring is needed but the check is operational.

### CODE REVIEW

**Comment by jherbel** [comment]
Hi, thank you for this PR. Unfortunately, we can at the moment only accept pure bug fixes, as stated in our contribution guidelines. Also, as you stated yourself, we would probably first need some refactoring here.

**Comment by LMS235** [comment]
But it would be nice if that could happen in a timely manner. The old solution was simply neglected for years.

**Comment by Yogibaer75** [comment]
> Hi, thank you for this PR. Unfortunately, we can at the moment only accept pure bug fixes, as stated in our contribution guidelines. Also, as you stated yourself, we would probably first need some refactoring here.

This is a bug fix as the old solution is not working anymore with CMK 2 and Python3.

**Comment by LMS235** [comment]
A few adjustments should be made, however. 

- Timeout parameter if system can not be reached (network, shutdown etc.) and then correct message the system is not available
- Errorhandling if something in the return value is not correct (e.g. incorrect values/config in the RZ20)

Currently, we help ourselves with very many SAP systems (~ 100) to store their own mk_sap_"landscape" scripts and then to work with their own configuration files (sap_"andscape".cfg) to use several processes at the same time (otherwise the mk_sap run would take too long until it is through all systems), perhaps there would be a nicer solution here that the script independently here several processes.  So when mk_sap is started on a central monitoring server.

**Comment by LMS235** [comment]
@jherbel / @LarsMichelsen is there already something new for this? a bit sad that you should "officially" still use the ancient python2 when there is already something (even if it should be adapted a bit).

**Comment by godspeed-you** [comment]
Just to inform the possible reader of this PR: I tried to describe our current problem with this PR in our [forum](https://forum.checkmk.com/t/mk-sap-py-python3-version/35106/2). Here's the quote, so don't need to click the link:

> Just a short update on this case. We’re currently working on an improvement regarding the efficiency/speed of our exporter. The first step is finished (adding metrics to the “OMD mysite performance” service). Please keep an eye to our werks, even if I try to spread the updates, e.g. to this topic.

Indeed, I am already in contact with a well known user. If the results are positive, I do see chances to merge the PR. There may be some changes needed, anyway.

**Comment by godspeed-you** [comment]
@stefan7018 I took some time here. We (tribe29) try to find a way to merge your changes. For that, we need some more things to do/adjust. Most likely it's about the problems mentioned by @LMS235. Please take a look at his suggestions. Some of them may need to split up into follow-up commits. Others may be integrated directly with this PR.  
I can understand, if you want to opt out of this PR. In this case, we would like to continue your work with some other users from our community. Please let us know if this is okay for you.

**Comment by LMS235** [comment]
And what we should not forget when it is addressed, SNC support for the connections. This is becoming more and more important.

**Comment by stefan7018** [comment]
> @stefan7018 I took some time here. We (tribe29) try to find a way to merge your changes. For that, we need some more things to do/adjust. Most likely it's about the problems mentioned by @LMS235. Please take a look at his suggestions. Some of them may need to split up into follow-up commits. Others may be integrated directly with this PR. I can understand, if you want to opt out of this PR. In this case, we would like to continue your work with some other users from our community. Please let us know if this is okay for you.

Hey @godspeed-you first thanks to take care about this topic! :) Actually I've no time to contribute here and implement this required changes so please take over and improve this PR. Let me know if you have any further questions.

**Comment by LMS235** [comment]
Is there a timeline in the meantime? Some things have been discussed. First and foremost, creating an officially supported state (python 3 and pyrfc) would be priority 1.

**Comment by godspeed-you** [comment]
Hi,
I'm currently waiting for another feedback. As soon as this is clarified, we can pick up this PR and merge the first step that has been made here.

**Comment by godspeed-you** [comment]
Small update on this one: One of our developers is currently preparing the merge.

**Comment by LMS235** [comment]
Good to hear, is there an approximate schedule yet?

Especially the issue that the "SAP State hostname" is also displayed on the system itself (and not only on the host on which mk_sap is running) would be extremely important.

**Comment by godspeed-you** [comment]
News on this case: My colleagues have been able to merge the changes. Thanks to all contributors and helping hands! You'll find the change in this commit: [3c6b70f75a7bbe2c69f80efdd800626255b63ef0](https://github.com/Checkmk/checkmk/commit/581011212eed44433c4c9c84fecf8e3e75e059e9)
Also in this werk: [#15545](https://checkmk.com/werk/15545)

**Pull request closed without merging**
