### PR TITLE
Support SCSI disk and update SATA check

### PR DESCRIPTION
**Pull request by truongtx8**
Sample output from SCSI disk:
```
smartctl -d scsi -A /dev/sde
smartctl 7.3 2022-02-28 r5338 [x86_64-linux-6.1.0-21-amd64] (local build)
Copyright (C) 2002-22, Bruce Allen, Christian Franke, www.smartmontools.org

=== START OF READ SMART DATA SECTION ===
Current Drive Temperature:     33 C
Drive Trip Temperature:        60 C

Accumulated power on time, hours:minutes 13323:18
Manufactured in week 17 of year 2021
Specified cycle count over device lifetime:  50000
Accumulated start-stop cycles:  26
Specified load-unload count over device lifetime:  600000
Accumulated load-unload cycles:  29313
Elements in grown defect list: 0
```

Thank you for your interest in contributing to Checkmk!
Consider looking into [Readme](https://github.com/Checkmk/checkmk#want-to-contribute) regarding process details.

## General information

Update script to get Power on time, Power cycle and Reallocated Sector count for SCSI disks.
Also update check command to modern SATA drives fall back instead of old ATA drives.

## Bug reports

Please include:

+ Your operating system name and version
+ Any details about your local setup that might be helpful in troubleshooting
+ Detailed steps to reproduce the bug
+ An agent output or SNMP walk
+ The ID of a submitted crash report for reference (if applicable)

## Proposed changes

Sometimes it is hard for us to assess the quality of a fix.
While it may work for you, it is our job to ensure that it works for everybody.
These are some ways to help us:

+ What is the expected behavior?
Returns check result for SCSI disks

+ What is the observed behavior?
```
<<<smart>>>
SEAGATE_XXX SEAGATE ST16000NM002G 194 Temperature_Celsius 0x0000 000 000 000 Old_age Always - 35 (0 0 0 0)
SEAGATE_XXX SEAGATE ST16000NM002G 9 Power_On_Hours 0x0000 000 000 000 Old_age Always - 13322
SEAGATE_XXX SEAGATE ST16000NM002G 12 Power_Cycle_Count 0x0000 000 000 000 Old_age Always - 26
SEAGATE_XXX SEAGATE ST16000NM002G 5 Reallocated_Sector_Ct 0x0000 000 000 000 Pre-fail Always - 0
```

+ If it's not obvious from the above: In what way does your patch change the current behavior?
+ Consider writing a unit test that would have failed without your fix.
+ Is this a new problem? What made you submit this PR (new firmware, new device, changed device behavior)?

### CODE REVIEW

**Comment by truongtx8** [comment]
I have read the CLA Document and I hereby sign the CLA or my organization already has a signed CLA.

**Comment by TimotheusBachinger** [comment]
Dear Checkmk Contributor! Unfortunately, we had to re-write our git-repo history, rendering your PR auto-closed. We will therefore rebase your PR onto the current master and reopen it again. Sorry for the inconvenience.

**Comment by TimotheusBachinger** [comment]
Dear Contributor. Unfortunately, we learned that re-opening a PR which was force-rebased, is not possible (see https://github.com/isaacs/github/issues/361). Therefore we kindly ask you to create a new PR for your change. We apologize for the circumstances and will implement technical measures to prevent such incidents in the future.

**Comment by truongtx8** [comment]
> Dear Contributor. Unfortunately, we learned that re-opening a PR which was force-rebased, is not possible (see [isaacs/github#361](https://github.com/isaacs/github/issues/361)). Therefore we kindly ask you to create a new PR for your change. We apologize for the circumstances and will implement technical measures to prevent such incidents in the future.

Hi @TimotheusBachinger,
I've created the new PR #714.

**Pull request closed without merging**
